# -*- coding: utf-8 -*-

#   2019/4/3 0003 下午 4:40     

__author__ = 'RollingBear'

from PyQt5 import QtCore, QtGui, QtWidgets


class ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(1280, 720)
        self.centralWidget = QtWidgets.QWidget(main_window)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontal_layout_2 = QtWidgets.QHBoxLayout()
        self.horizontal_layout_2.setObjectName("horizontal_layout_2")
        self.horizontal_layout_1 = QtWidgets.QHBoxLayout()
        self.horizontal_layout_1.setObjectName("horizontal_layout_1")
        self.new_button = QtWidgets.QPushButton(self.centralWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/res/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_button.setIcon(icon)
        self.new_button.setObjectName("new_button")
        self.horizontal_layout_1.addWidget(self.new_button)
        self.home_button = QtWidgets.QPushButton(self.centralWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/res/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_button.setIcon(icon1)
        self.home_button.setObjectName("home_button")
        self.horizontal_layout_1.addWidget(self.home_button)
        self.forward_button = QtWidgets.QPushButton(self.centralWidget)
        self.forward_button.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/res/forward.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forward_button.setIcon(icon2)
        self.forward_button.setObjectName("forward_button")
        self.horizontal_layout_1.addWidget(self.forward_button)
        self.back_button = QtWidgets.QPushButton(self.centralWidget)
        self.back_button.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/res/back.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_button.setIcon(icon3)
        self.back_button.setObjectName("back_button")
        self.horizontal_layout_1.addWidget(self.back_button)
        self.refresh_button = QtWidgets.QPushButton(self.centralWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/res/reload.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_button.setIcon(icon4)
        self.refresh_button.setObjectName("refresh_button")
        self.horizontal_layout_1.addWidget(self.refresh_button)
        self.stop_button = QtWidgets.QPushButton(self.centralWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/res/stop.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_button.setIcon(icon5)
        self.stop_button.setObjectName("stop_button")
        self.horizontal_layout_1.addWidget(self.stop_button)
        self.lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontal_layout_1.addWidget(self.lineEdit)
        self.horizontal_layout_2.addLayout(self.horizontal_layout_1)
        self.progressBar = QtWidgets.QProgressBar(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontal_layout_2.addWidget(self.progressBar)
        self.go_button = QtWidgets.QPushButton(self.centralWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/res/go.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.go_button.setIcon(icon6)
        self.go_button.setObjectName("go_button")
        self.horizontal_layout_2.addWidget(self.go_button)
        self.verticalLayout.addLayout(self.horizontal_layout_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout.addWidget(self.tabWidget)
        main_window.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(main_window)
        self.statusBar.setObjectName("statusBar")
        main_window.setStatusBar(self.statusBar)

        self.retranslateUi(main_window)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "PyQt Browser 1.1.0a"))
        self.new_button.setText(_translate("main_window", "New Page"))
        self.home_button.setText(_translate("main_window", "Home Page"))
        self.forward_button.setText(_translate("main_window", "Forward"))
        self.back_button.setText(_translate("main_window", "Back"))
        self.refresh_button.setText(_translate("main_window", "Refresh"))
        self.stop_button.setText(_translate("main_window", "Stop"))
        self.go_button.setText(_translate("main_window", "GO"))


import browser_bate_1_1_0.res_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.Qmain_window()
    ui = ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
